### PR TITLE
Introduced wrapper classes for handles, moved handle related function…

### PR DESCRIPTION
**Pull request by asuessenbach**
…s into those classes; introduced exceptions for error handling.

### CODE REVIEW

**Comment by Trass3r** [comment]
What if exceptions are disabled?
Shouldn't be uncommon in the games industry.

**Comment by mtavenrath** [comment]
Due to the exponential explosion supporting any combination of handles/exceptions/stl/... we decided to have just two modes for now
* One 'just typesafe' mode for the vk::* function which accept the handles. This mode doesn't need exceptions or STL which depends on exceptions.

* One mode with exceptions and STL and member functions in the handles.

It's still useful to use just the standard mode by not defining VKCPP_ENHANCED_MODE.

**Comment by Trass3r** [comment]
I see.
Having classes with methods wrapping the calls is _the_ reason for using this though.
And at least both libstdc++ and MS STL (when defining _HAS_EXCEPTIONS=0) work without exceptions.
Just my 2 cents ;)

**Comment by mtavenrath** [comment]
We're thinking about adding the non-STL versions of the functions to the classes. Once those are in they'll be enabled outside of the enhanced mode. In this case you'll have member functions, but not the simplicity of the vectors.

**Comment by Trass3r** [comment]
That would be good. In general non-stl overloads for the methods taking string or vector parameters are desirable. If you pass in a string literal for example there is an unnecessary allocation and array data does not always come in std::vector form either.

**Pull request merged**
